services:
  viren.api:
    image: ${IMAGE_NAME:-duythong2/virenapi}:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Viren.API/Dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest

  postgres:
    image: postgres:16-alpine

  messagebroker:
    image: rabbitmq:management
  
  chroma:
    image: chromadb/chroma:latest